# Generated by Django 5.1.4 on 2025-08-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
