# Generated by Django 5.1.4 on 2025-08-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('required_documents', models.TextField()),
                ('process', models.TextField()),
                ('office_address', models.CharField(max_length=300)),
                ('office_contact', models.CharField(max_length=50)),
                ('office_hours', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificate_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
