# Generated by Django 5.1.4 on 2025-08-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
