# Generated by Django 5.1.4 on 2025-08-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='office_contact',
            field=models.CharField(max_length=500),
        ),
    ]
