# Generated by Django 5.1.4 on 2025-08-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_user_email_otp_user_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
